# Generated by Django 5.2.6 on 2025-09-19 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_agora_channel_event_agora_resource_id_and_more'),
        ('organizations', '0002_alter_organization_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_cents', models.PositiveIntegerField(help_text='Ticket price in cents')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Corresponding Stripe Price identifier', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_plans', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Associated Stripe PaymentIntent identifier', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('amount_cents', models.PositiveIntegerField(help_text='Charged amount in cents')),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to='events.event')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='payments.ticketplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketplan',
            index=models.Index(fields=['organization', 'is_active'], name='payments_ti_organiz_6d8d20_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['event', 'user', 'status'], name='payments_ti_event_i_f7bb58_idx'),
        ),
    ]
