# Generated by Django 5.2.6 on 2025-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agora_channel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='agora_resource_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='agora_sid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
