version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ecp}
      POSTGRES_USER: ${POSTGRES_USER:-ecp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ecp_password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 ecp_backend.asgi:application
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    command: celery -A ecp_backend.celery_app worker -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A ecp_backend.celery_app beat -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata: