# Generated by Django 5.2.6 on 2025-09-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_agora_channel_event_agora_resource_id_and_more'),
        ('organizations', '0002_alter_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('resource_count', models.PositiveIntegerField(default=0)),
                ('registrations_count', models.PositiveIntegerField(default=0)),
                ('purchases_count', models.PositiveIntegerField(default=0)),
                ('revenue_cents', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_dailies', to='events.event')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_dailies', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('organization', 'event', 'date')},
            },
        ),
    ]
