"""
Serializers for the blog APIs.

Reader-facing serializers (list/detail) expose only display data. The admin
serializer also exposes audit and WordPress source fields, but keeps them
read-only: audit fields are set by the views, and WordPress fields belong to
the future importer. ``status``/``published_at`` change only through the
explicit publish/unpublish actions.
"""
from django.contrib.auth import get_user_model
from rest_framework import serializers

from users.serializers import UserMiniSerializer

from .models import RESERVED_SLUGS, BlogCategory, BlogPost, BlogTag

User = get_user_model()

FEATURED_IMAGE_MAX_BYTES = 10 * 1024 * 1024


class BlogAuthorSerializer(UserMiniSerializer):
    """Public author card: display name and avatar only (no email/username)."""

    class Meta(UserMiniSerializer.Meta):
        fields = ("id", "full_name", "avatar_url")

    def get_full_name(self, obj) -> str:
        computed = f"{obj.first_name or ''} {obj.last_name or ''}".strip()
        if computed:
            return computed
        profile = getattr(obj, "profile", None)
        return (getattr(profile, "full_name", "") or "") if profile else ""

    def get_avatar_url(self, obj) -> str:
        return super().get_avatar_url(obj)


class BlogTermSummarySerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    name = serializers.CharField(read_only=True)
    slug = serializers.CharField(read_only=True)


def _validate_unique_slug(serializer, value, model):
    value = (value or "").strip()
    if not value:
        if serializer.instance is not None:
            raise serializers.ValidationError("Slug cannot be blank.")
        return ""  # generated by the model on save
    qs = model.objects.filter(slug__iexact=value)
    if serializer.instance is not None:
        qs = qs.exclude(pk=serializer.instance.pk)
    if qs.exists():
        raise serializers.ValidationError("This slug is already in use.")
    return value


class BlogTermSerializer(serializers.ModelSerializer):
    slug = serializers.SlugField(max_length=140, required=False, allow_blank=True)

    class Meta:
        fields = ("id", "name", "slug", "created_at", "updated_at")
        read_only_fields = ("id", "created_at", "updated_at")

    def validate_name(self, value):
        value = value.strip()
        qs = self.Meta.model.objects.filter(name__iexact=value)
        if self.instance is not None:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise serializers.ValidationError("An entry with this name already exists.")
        return value

    def validate_slug(self, value):
        return _validate_unique_slug(self, value, self.Meta.model)


class BlogCategorySerializer(BlogTermSerializer):
    class Meta(BlogTermSerializer.Meta):
        model = BlogCategory


class BlogTagSerializer(BlogTermSerializer):
    class Meta(BlogTermSerializer.Meta):
        model = BlogTag


class BlogListSerializer(serializers.ModelSerializer):
    author = BlogAuthorSerializer(read_only=True)
    categories = BlogTermSummarySerializer(many=True, read_only=True)
    tags = BlogTermSummarySerializer(many=True, read_only=True)

    class Meta:
        model = BlogPost
        fields = (
            "id",
            "title",
            "slug",
            "excerpt",
            "featured_image",
            "author",
            "legacy_author_name",
            "published_at",
            "categories",
            "tags",
        )
        read_only_fields = fields


class BlogDetailSerializer(BlogListSerializer):
    class Meta(BlogListSerializer.Meta):
        fields = BlogListSerializer.Meta.fields + (
            "content_html",
            "seo_title",
            "seo_description",
            "canonical_url",
            "updated_at",
        )
        read_only_fields = fields


class BlogAdminSerializer(serializers.ModelSerializer):
    slug = serializers.SlugField(max_length=255, required=False, allow_blank=True)
    author = BlogAuthorSerializer(read_only=True)
    author_id = serializers.PrimaryKeyRelatedField(
        source="author",
        queryset=User.objects.all(),
        allow_null=True,
        required=False,
        write_only=True,
    )
    categories = BlogTermSummarySerializer(many=True, read_only=True)
    category_ids = serializers.PrimaryKeyRelatedField(
        source="categories",
        queryset=BlogCategory.objects.all(),
        many=True,
        required=False,
        write_only=True,
    )
    tags = BlogTermSummarySerializer(many=True, read_only=True)
    tag_ids = serializers.PrimaryKeyRelatedField(
        source="tags",
        queryset=BlogTag.objects.all(),
        many=True,
        required=False,
        write_only=True,
    )
    created_by = BlogAuthorSerializer(read_only=True)
    updated_by = BlogAuthorSerializer(read_only=True)

    class Meta:
        model = BlogPost
        fields = (
            "id",
            "title",
            "slug",
            "excerpt",
            "content_html",
            "featured_image",
            "author",
            "author_id",
            "legacy_author_name",
            "status",
            "published_at",
            "categories",
            "category_ids",
            "tags",
            "tag_ids",
            "seo_title",
            "seo_description",
            "canonical_url",
            "wp_post_id",
            "wp_source_url",
            "wp_author_id",
            "wp_modified_at",
            "imported_from_wordpress",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
        )
        read_only_fields = (
            "id",
            "status",
            "published_at",
            "wp_post_id",
            "wp_source_url",
            "wp_author_id",
            "wp_modified_at",
            "imported_from_wordpress",
            "created_at",
            "updated_at",
        )

    def validate_slug(self, value):
        if (value or "").strip().lower() in RESERVED_SLUGS:
            raise serializers.ValidationError("This slug is reserved.")
        return _validate_unique_slug(self, value, BlogPost)

    def validate_featured_image(self, value):
        if value and getattr(value, "size", 0) > FEATURED_IMAGE_MAX_BYTES:
            raise serializers.ValidationError("Featured image must be 10 MB or smaller.")
        return value

    def validate(self, attrs):
        # A live article must stay publishable while it is being edited.
        instance = self.instance
        if instance is not None and instance.is_published:
            title = attrs.get("title", instance.title)
            content = attrs.get("content_html", instance.content_html)
            errors = BlogPost(title=title, content_html=content).publishability_errors()
            if errors:
                raise serializers.ValidationError(errors)
        return attrs


class BlogPublishSerializer(serializers.Serializer):
    """Empty body for publish/unpublish actions (keeps the schema explicit)."""
