"""Schemas for post-acceptance forms."""
from .promotional_profile_speaker import SPEAKER_MODULE_SCHEMA, SPEAKER_VALIDATION_RULES
from .promotional_profile_modules import (
    SPONSOR_ORGANISATION_MODULE_SCHEMA,
    SPONSOR_STAFF_MODULE_SCHEMA,
    STARTUP_MODULE_SCHEMA,
    INVESTOR_MODULE_SCHEMA,
    SPONSOR_VALIDATION_RULES,
    SPONSOR_STAFF_VALIDATION_RULES,
    STARTUP_VALIDATION_RULES,
    INVESTOR_VALIDATION_RULES
)

__all__ = [
    'SPEAKER_MODULE_SCHEMA',
    'SPEAKER_VALIDATION_RULES',
    'SPONSOR_ORGANISATION_MODULE_SCHEMA',
    'SPONSOR_STAFF_MODULE_SCHEMA',
    'STARTUP_MODULE_SCHEMA',
    'INVESTOR_MODULE_SCHEMA',
    'SPONSOR_VALIDATION_RULES',
    'SPONSOR_STAFF_VALIDATION_RULES',
    'STARTUP_VALIDATION_RULES',
    'INVESTOR_VALIDATION_RULES'
]
