"""Tests for UserSerializer.provider.

The Security card in the frontend uses this field to decide whether a user can
change their password in place (native Cognito accounts) or must set one
through the reset flow (federated accounts, whose Cognito password was
generated by the backend during login bootstrap and is unknown to them).
"""

from django.contrib.auth.models import User
from django.test import TestCase

from users.models import CognitoIdentity
from users.serializers import UserSerializer


class _FakeRequest:
    """Stands in for a DRF request carrying Cognito claims."""

    def __init__(self, claims=None):
        if claims is not None:
            self.cognito_claims = claims


class UserSerializerProviderTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="provider-member",
            email="provider-member@example.com",
            password="ValidPassword123!",
        )

    def _provider(self, context=None):
        return UserSerializer(self.user, context=context or {}).data.get("provider")

    def test_defaults_to_cognito_without_identity_or_claims(self):
        """Unknown accounts must keep the existing change-password behaviour."""
        self.assertEqual(self._provider(), "cognito")

    def test_uses_stored_identity_for_google_user(self):
        CognitoIdentity.objects.create(
            user=self.user,
            cognito_sub="sub-google-1",
            email=self.user.email,
            email_verified=True,
            provider="google",
        )

        self.assertEqual(self._provider(), "google")

    def test_uses_stored_identity_for_native_user(self):
        CognitoIdentity.objects.create(
            user=self.user,
            cognito_sub="sub-cognito-1",
            email=self.user.email,
            email_verified=True,
            provider="cognito",
        )

        self.assertEqual(self._provider(), "cognito")

    def test_request_claims_take_precedence_over_stored_identity(self):
        """The answer should reflect how the user signed in for this request."""
        CognitoIdentity.objects.create(
            user=self.user,
            cognito_sub="sub-cognito-2",
            email=self.user.email,
            email_verified=True,
            provider="cognito",
        )

        request = _FakeRequest(
            {
                "cognito:username": "google_104338173680362243999",
                "identities": [{"providerName": "Google"}],
            }
        )

        self.assertEqual(self._provider({"request": request}), "google")

    def test_provider_inferred_from_username_prefix_when_identities_absent(self):
        """Access tokens omit `identities`; the username prefix is the fallback."""
        request = _FakeRequest({"cognito:username": "google_104338173680362243999"})

        self.assertEqual(self._provider({"request": request}), "google")

    def test_request_without_claims_falls_back_to_identity(self):
        CognitoIdentity.objects.create(
            user=self.user,
            cognito_sub="sub-google-2",
            email=self.user.email,
            email_verified=True,
            provider="google",
        )

        self.assertEqual(self._provider({"request": _FakeRequest()}), "google")

    def test_provider_is_read_only(self):
        """`provider` is derived state and must never be writable."""
        serializer = UserSerializer(
            self.user,
            data={"provider": "cognito", "username": "provider-member"},
            partial=True,
        )
        self.assertTrue(serializer.is_valid(), serializer.errors)
        self.assertNotIn("provider", serializer.validated_data)
