from django.urls import path

from .admin_views import (
    NewsletterAdminAudienceDetailView,
    NewsletterAdminAudienceListCreateView,
    NewsletterAdminCampaignAnalyticsView,
    NewsletterAdminCampaignCancelView,
    NewsletterAdminCampaignDetailView,
    NewsletterAdminCampaignListCreateView,
    NewsletterAdminCampaignPreviewView,
    NewsletterAdminCampaignScheduleView,
    NewsletterAdminCampaignSendView,
    NewsletterAdminCampaignSyncView,
    NewsletterAdminCampaignTestEmailView,
    NewsletterAdminCategoryDetailView,
    NewsletterAdminCategoryLinkMauticSegmentView,
    NewsletterAdminCategoryListView,
)
from .views import NewsletterPreferencesView
from .webhooks import MauticNewsletterWebhookView


urlpatterns = [
    path(
        "newsletter/preferences/",
        NewsletterPreferencesView.as_view(),
        name="newsletter-preferences",
    ),
    path(
        "newsletter/admin/audiences/",
        NewsletterAdminAudienceListCreateView.as_view(),
        name="newsletter-admin-audience-list",
    ),
    path(
        "newsletter/admin/audiences/<uuid:uuid>/",
        NewsletterAdminAudienceDetailView.as_view(),
        name="newsletter-admin-audience-detail",
    ),
    path(
        "newsletter/admin/campaigns/",
        NewsletterAdminCampaignListCreateView.as_view(),
        name="newsletter-admin-campaign-list",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/",
        NewsletterAdminCampaignDetailView.as_view(),
        name="newsletter-admin-campaign-detail",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/preview/",
        NewsletterAdminCampaignPreviewView.as_view(),
        name="newsletter-admin-campaign-preview",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/analytics/",
        NewsletterAdminCampaignAnalyticsView.as_view(),
        name="newsletter-admin-campaign-analytics",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/test-email/",
        NewsletterAdminCampaignTestEmailView.as_view(),
        name="newsletter-admin-campaign-test-email",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/sync/",
        NewsletterAdminCampaignSyncView.as_view(),
        name="newsletter-admin-campaign-sync",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/send/",
        NewsletterAdminCampaignSendView.as_view(),
        name="newsletter-admin-campaign-send",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/schedule/",
        NewsletterAdminCampaignScheduleView.as_view(),
        name="newsletter-admin-campaign-schedule",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/cancel/",
        NewsletterAdminCampaignCancelView.as_view(),
        name="newsletter-admin-campaign-cancel",
    ),
    path(
        "newsletter/admin/categories/",
        NewsletterAdminCategoryListView.as_view(),
        name="newsletter-admin-category-list",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/",
        NewsletterAdminCategoryDetailView.as_view(),
        name="newsletter-admin-category-detail",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/link-mautic-segment/",
        NewsletterAdminCategoryLinkMauticSegmentView.as_view(),
        name="newsletter-admin-category-link-mautic-segment",
    ),
    path(
        "newsletter/webhooks/mautic/",
        MauticNewsletterWebhookView.as_view(),
        name="newsletter-mautic-webhook",
    ),
]
