from django.urls import path

from .admin_views import (
    NewsletterAdminAudienceDetailView,
    NewsletterAdminAudienceListCreateView,
    NewsletterAdminCampaignAnalyticsView,
    NewsletterAdminCampaignCancelView,
    NewsletterAdminCampaignDetailView,
    NewsletterAdminCampaignListCreateView,
    NewsletterAdminCampaignPreviewView,
    NewsletterAdminCampaignScheduleView,
    NewsletterAdminCampaignSendView,
    NewsletterAdminCampaignSyncView,
    NewsletterAdminCampaignTestEmailView,
    NewsletterAdminContactActivityView,
    NewsletterAdminContactBulkStageView,
    NewsletterAdminContactCompaniesView,
    NewsletterAdminContactDetailView,
    NewsletterAdminContactDncDetailView,
    NewsletterAdminContactDncView,
    NewsletterAdminContactEngagementView,
    NewsletterAdminContactFieldMetadataView,
    NewsletterAdminContactNotesView,
    NewsletterAdminContactListView,
    NewsletterAdminContactStageView,
    NewsletterAdminContactTagDetailView,
    NewsletterAdminContactTagsView,
    NewsletterAdminTagListView,
    NewsletterAdminCategoryContactAnalyticsView,
    NewsletterAdminCategoryContactsView,
    NewsletterAdminCategoryDetailView,
    NewsletterAdminCategoryLinkMauticSegmentView,
    NewsletterAdminCategoryListView,
    NewsletterAdminCategorySyncMauticView,
    NewsletterAdminMauticSegmentListView,
    NewsletterAdminMauticSegmentDetailView,
    NewsletterAdminMauticSegmentContactDetailView,
    NewsletterAdminMauticSegmentContactsView,
    NewsletterAdminStageAnalyticsView,
    NewsletterAdminStageDetailView,
    NewsletterAdminStageListCreateView,
)
from .point_group_views import (
    NewsletterAdminContactPointGroupDetailView,
    NewsletterAdminContactPointGroupsView,
    NewsletterAdminPointGroupDeleteCheckView,
    NewsletterAdminPointGroupDetailView,
    NewsletterAdminPointGroupListCreateView,
)
from .point_trigger_views import (
    NewsletterAdminPointTriggerDetailView,
    NewsletterAdminPointTriggerEventDetailView,
    NewsletterAdminPointTriggerEventListCreateView,
    NewsletterAdminPointTriggerEventTypesView,
    NewsletterAdminPointTriggerListCreateView,
)
from .point_views import (
    NewsletterAdminContactPointsView,
    NewsletterAdminPointActionDetailView,
    NewsletterAdminPointActionListCreateView,
    NewsletterAdminPointActionTypesView,
)
from .template_views import (
    NewsletterAdminTemplateDetailView,
    NewsletterAdminTemplateListCreateView,
)
from .native_campaign_views import (
    NewsletterAdminMauticCampaignBuilderView,
    NewsletterAdminMauticCampaignCapabilitiesView,
    NewsletterAdminMauticCampaignDetailView,
    NewsletterAdminMauticCampaignListCreateView,
)
from .company_views import (
    NewsletterAdminCompanyContactDetailView,
    NewsletterAdminCompanyContactsView,
    NewsletterAdminCompanyDetailView,
    NewsletterAdminCompanyListCreateView,
)
from .field_views import (
    NewsletterAdminFieldChoicesView,
    NewsletterAdminFieldDetailView,
    NewsletterAdminFieldListCreateView,
    NewsletterAdminFieldTypesView,
)
from .tag_views import (
    NewsletterAdminTagDetailView,
    NewsletterAdminTagDirectoryView,
)
from .views import NewsletterPreferencesView
from .webhooks import MauticNewsletterWebhookView


urlpatterns = [
    path(
        "newsletter/preferences/",
        NewsletterPreferencesView.as_view(),
        name="newsletter-preferences",
    ),
    path(
        "newsletter/admin/audiences/",
        NewsletterAdminAudienceListCreateView.as_view(),
        name="newsletter-admin-audience-list",
    ),
    path(
        "newsletter/admin/audiences/<uuid:uuid>/",
        NewsletterAdminAudienceDetailView.as_view(),
        name="newsletter-admin-audience-detail",
    ),
    path(
        "newsletter/admin/campaigns/",
        NewsletterAdminCampaignListCreateView.as_view(),
        name="newsletter-admin-campaign-list",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/",
        NewsletterAdminCampaignDetailView.as_view(),
        name="newsletter-admin-campaign-detail",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/preview/",
        NewsletterAdminCampaignPreviewView.as_view(),
        name="newsletter-admin-campaign-preview",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/analytics/",
        NewsletterAdminCampaignAnalyticsView.as_view(),
        name="newsletter-admin-campaign-analytics",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/test-email/",
        NewsletterAdminCampaignTestEmailView.as_view(),
        name="newsletter-admin-campaign-test-email",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/sync/",
        NewsletterAdminCampaignSyncView.as_view(),
        name="newsletter-admin-campaign-sync",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/send/",
        NewsletterAdminCampaignSendView.as_view(),
        name="newsletter-admin-campaign-send",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/schedule/",
        NewsletterAdminCampaignScheduleView.as_view(),
        name="newsletter-admin-campaign-schedule",
    ),
    path(
        "newsletter/admin/campaigns/<uuid:uuid>/cancel/",
        NewsletterAdminCampaignCancelView.as_view(),
        name="newsletter-admin-campaign-cancel",
    ),
    # Native provider-owned Mautic Campaign API. This intentionally uses a
    # separate path while the legacy ECP NewsletterCampaign endpoints are
    # still present for safe migration and historical compatibility.
    path(
        "newsletter/admin/mautic-campaigns/",
        NewsletterAdminMauticCampaignListCreateView.as_view(),
        name="newsletter-admin-mautic-campaign-list",
    ),
    path(
        "newsletter/admin/mautic-campaigns/capabilities/",
        NewsletterAdminMauticCampaignCapabilitiesView.as_view(),
        name="newsletter-admin-mautic-campaign-capabilities",
    ),
    path(
        "newsletter/admin/mautic-campaigns/<str:campaign_id>/",
        NewsletterAdminMauticCampaignDetailView.as_view(),
        name="newsletter-admin-mautic-campaign-detail",
    ),
    path(
        "newsletter/admin/mautic-campaigns/<str:campaign_id>/builder/",
        NewsletterAdminMauticCampaignBuilderView.as_view(),
        name="newsletter-admin-mautic-campaign-builder",
    ),
    path(
        "newsletter/admin/categories/",
        NewsletterAdminCategoryListView.as_view(),
        name="newsletter-admin-category-list",
    ),
    path(
        "newsletter/admin/templates/",
        NewsletterAdminTemplateListCreateView.as_view(),
        name="newsletter-admin-template-list",
    ),
    path(
        "newsletter/admin/templates/<str:template_id>/",
        NewsletterAdminTemplateDetailView.as_view(),
        name="newsletter-admin-template-detail",
    ),
    path(
        "newsletter/admin/contacts/",
        NewsletterAdminContactListView.as_view(),
        name="newsletter-admin-contact-list",
    ),
    path(
        "newsletter/admin/contacts/bulk-stage/",
        NewsletterAdminContactBulkStageView.as_view(),
        name="newsletter-admin-contact-bulk-stage",
    ),
    path(
        "newsletter/admin/contacts/field-metadata/",
        NewsletterAdminContactFieldMetadataView.as_view(),
        name="newsletter-admin-contact-field-metadata",
    ),
    path(
        "newsletter/admin/tags/",
        NewsletterAdminTagListView.as_view(),
        name="newsletter-admin-tag-list",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/points/",
        NewsletterAdminContactPointsView.as_view(),
        name="newsletter-admin-contact-points",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/stage/",
        NewsletterAdminContactStageView.as_view(),
        name="newsletter-admin-contact-stage",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/activity/",
        NewsletterAdminContactActivityView.as_view(),
        name="newsletter-admin-contact-activity",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/engagement-analytics/",
        NewsletterAdminContactEngagementView.as_view(),
        name="newsletter-admin-contact-engagement",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/tags/",
        NewsletterAdminContactTagsView.as_view(),
        name="newsletter-admin-contact-tags",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/tags/<str:tag>/",
        NewsletterAdminContactTagDetailView.as_view(),
        name="newsletter-admin-contact-tag-detail",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/notes/",
        NewsletterAdminContactNotesView.as_view(),
        name="newsletter-admin-contact-notes",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/dnc/",
        NewsletterAdminContactDncView.as_view(),
        name="newsletter-admin-contact-dnc",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/dnc/<str:channel>/",
        NewsletterAdminContactDncDetailView.as_view(),
        name="newsletter-admin-contact-dnc-detail",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/companies/",
        NewsletterAdminContactCompaniesView.as_view(),
        name="newsletter-admin-contact-companies",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/",
        NewsletterAdminContactDetailView.as_view(),
        name="newsletter-admin-contact-detail",
    ),
    path(
        "newsletter/admin/points/types/",
        NewsletterAdminPointActionTypesView.as_view(),
        name="newsletter-admin-point-action-types",
    ),
    path(
        "newsletter/admin/points/",
        NewsletterAdminPointActionListCreateView.as_view(),
        name="newsletter-admin-point-action-list",
    ),
    path(
        "newsletter/admin/points/groups/",
        NewsletterAdminPointGroupListCreateView.as_view(),
        name="newsletter-admin-point-group-list",
    ),
    path(
        "newsletter/admin/points/groups/<str:group_id>/delete-check/",
        NewsletterAdminPointGroupDeleteCheckView.as_view(),
        name="newsletter-admin-point-group-delete-check",
    ),
    path(
        "newsletter/admin/points/groups/<str:group_id>/",
        NewsletterAdminPointGroupDetailView.as_view(),
        name="newsletter-admin-point-group-detail",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/point-groups/",
        NewsletterAdminContactPointGroupsView.as_view(),
        name="newsletter-admin-contact-point-group-list",
    ),
    path(
        "newsletter/admin/contacts/<str:mautic_contact_id>/point-groups/<str:group_id>/",
        NewsletterAdminContactPointGroupDetailView.as_view(),
        name="newsletter-admin-contact-point-group-detail",
    ),
    path(
        "newsletter/admin/points/triggers/event-types/",
        NewsletterAdminPointTriggerEventTypesView.as_view(),
        name="newsletter-admin-point-trigger-event-types",
    ),
    path(
        "newsletter/admin/points/triggers/",
        NewsletterAdminPointTriggerListCreateView.as_view(),
        name="newsletter-admin-point-trigger-list",
    ),
    path(
        "newsletter/admin/points/triggers/<str:trigger_id>/events/",
        NewsletterAdminPointTriggerEventListCreateView.as_view(),
        name="newsletter-admin-point-trigger-event-list",
    ),
    path(
        "newsletter/admin/points/triggers/<str:trigger_id>/events/<str:event_id>/",
        NewsletterAdminPointTriggerEventDetailView.as_view(),
        name="newsletter-admin-point-trigger-event-detail",
    ),
    path(
        "newsletter/admin/points/triggers/<str:trigger_id>/",
        NewsletterAdminPointTriggerDetailView.as_view(),
        name="newsletter-admin-point-trigger-detail",
    ),
    path(
        "newsletter/admin/points/<str:point_id>/",
        NewsletterAdminPointActionDetailView.as_view(),
        name="newsletter-admin-point-action-detail",
    ),
    path(
        "newsletter/admin/stages/",
        NewsletterAdminStageListCreateView.as_view(),
        name="newsletter-admin-stage-list",
    ),
    path(
        "newsletter/admin/stages/analytics/",
        NewsletterAdminStageAnalyticsView.as_view(),
        name="newsletter-admin-stage-analytics",
    ),
    path(
        "newsletter/admin/stages/<str:stage_id>/",
        NewsletterAdminStageDetailView.as_view(),
        name="newsletter-admin-stage-detail",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/contact-analytics/",
        NewsletterAdminCategoryContactAnalyticsView.as_view(),
        name="newsletter-admin-category-contact-analytics",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/contacts/",
        NewsletterAdminCategoryContactsView.as_view(),
        name="newsletter-admin-category-contacts",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/",
        NewsletterAdminCategoryDetailView.as_view(),
        name="newsletter-admin-category-detail",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/link-mautic-segment/",
        NewsletterAdminCategoryLinkMauticSegmentView.as_view(),
        name="newsletter-admin-category-link-mautic-segment",
    ),
    path(
        "newsletter/admin/categories/<slug:slug>/sync-mautic/",
        NewsletterAdminCategorySyncMauticView.as_view(),
        name="newsletter-admin-category-sync-mautic",
    ),
    path(
        "newsletter/admin/mautic/segments/",
        NewsletterAdminMauticSegmentListView.as_view(),
        name="newsletter-admin-mautic-segment-list",
    ),
    path(
        "newsletter/admin/mautic/segments/<str:segment_id>/",
        NewsletterAdminMauticSegmentDetailView.as_view(),
        name="newsletter-admin-mautic-segment-detail",
    ),
    path(
        "newsletter/admin/mautic/segments/<str:segment_id>/contacts/",
        NewsletterAdminMauticSegmentContactsView.as_view(),
        name="newsletter-admin-mautic-segment-contact-list",
    ),
    path(
        "newsletter/admin/mautic/segments/<str:segment_id>/contacts/<str:contact_id>/",
        NewsletterAdminMauticSegmentContactDetailView.as_view(),
        name="newsletter-admin-mautic-segment-contact-detail",
    ),
    path(
        "newsletter/admin/companies/",
        NewsletterAdminCompanyListCreateView.as_view(),
        name="newsletter-admin-company-list",
    ),
    path(
        "newsletter/admin/companies/<str:company_id>/",
        NewsletterAdminCompanyDetailView.as_view(),
        name="newsletter-admin-company-detail",
    ),
    path(
        "newsletter/admin/companies/<str:company_id>/contacts/",
        NewsletterAdminCompanyContactsView.as_view(),
        name="newsletter-admin-company-contact-list",
    ),
    path(
        "newsletter/admin/companies/<str:company_id>/contacts/<str:contact_id>/",
        NewsletterAdminCompanyContactDetailView.as_view(),
        name="newsletter-admin-company-contact-detail",
    ),
    path(
        "newsletter/admin/tags/directory/",
        NewsletterAdminTagDirectoryView.as_view(),
        name="newsletter-admin-tag-directory",
    ),
    path(
        "newsletter/admin/tags/directory/<str:tag_id>/",
        NewsletterAdminTagDetailView.as_view(),
        name="newsletter-admin-tag-detail",
    ),
    path(
        "newsletter/admin/fields/types/",
        NewsletterAdminFieldTypesView.as_view(),
        name="newsletter-admin-field-types",
    ),
    path(
        "newsletter/admin/fields/choices/<str:field_type>/",
        NewsletterAdminFieldChoicesView.as_view(),
        name="newsletter-admin-field-choices",
    ),
    path(
        "newsletter/admin/fields/<str:field_object>/",
        NewsletterAdminFieldListCreateView.as_view(),
        name="newsletter-admin-field-list",
    ),
    path(
        "newsletter/admin/fields/<str:field_object>/<str:field_id>/",
        NewsletterAdminFieldDetailView.as_view(),
        name="newsletter-admin-field-detail",
    ),
    path(
        "newsletter/webhooks/mautic/",
        MauticNewsletterWebhookView.as_view(),
        name="newsletter-mautic-webhook",
    ),
]
